source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CLCocoaExtension_Example', :exclusive => true do
  pod "CLCocoaExtension", :path => "../"
end

target 'CLCocoaExtension_Tests', :exclusive => true do
  pod "CLCocoaExtension", :path => "../"

  pod 'FBSnapshotTestCase'
end
